"""initial1

Revision ID: 29510c0b5830
Revises: 
Create Date: 2018-08-13 23:55:43.770051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29510c0b5830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_column('name1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name1', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
