"""add "confirmed" to user model

Revision ID: 452016aa1fb7
Revises: c3ee16db34df
Create Date: 2018-08-28 17:00:53.332614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452016aa1fb7'
down_revision = 'c3ee16db34df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
