"""add column Post.digest

Revision ID: a064f648e0a9
Revises: 4dfdf09dc5ce
Create Date: 2018-10-10 23:14:40.142157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a064f648e0a9'
down_revision = '4dfdf09dc5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digest', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('digest')

    # ### end Alembic commands ###
