"""test end

Revision ID: ad957f274d79
Revises: b516d3fe3f09
Create Date: 2018-08-14 13:13:30.093975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad957f274d79'
down_revision = 'b516d3fe3f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roles_name1', type_='unique')
        batch_op.drop_constraint('uq_roles_name2', type_='unique')
        batch_op.drop_column('name1')
        batch_op.drop_column('name2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name2', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('name1', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_roles_name2', ['name2'])
        batch_op.create_unique_constraint('uq_roles_name1', ['name1'])

    # ### end Alembic commands ###
