"""second_migrate

Revision ID: bb9a3eb8a5fb
Revises: 29510c0b5830
Create Date: 2018-08-14 12:02:03.291673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import UniqueConstraint

revision = 'bb9a3eb8a5fb'
down_revision = '29510c0b5830'
branch_labels = None
depends_on = None
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint('uq_roles_id', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('uq_roles_id', type_='unique')

    # ### end Alembic commands ###
