"""empty message

Revision ID: c78156c0a883
Revises: 
Create Date: 2018-08-12 22:32:00.377929

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c78156c0a883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'users', ['name'])
    # op.drop_column('users', 'username')
    op.alter_column(table_name='users',column_name='username',new_column_name='name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=True))
    # op.drop_constraint(None, 'users', type_='unique')
    # op.drop_column('users', 'name')
    op.alter_column(table_name='users', column_name='name', new_column_name='username')
    # ### end Alembic commands ###
