"""normalize

Revision ID: e7538ba2bca8
Revises: ad957f274d79
Create Date: 2018-08-14 23:17:06.750711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7538ba2bca8'
down_revision = 'ad957f274d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_constraint('uq_users_name555', type_='unique')
        batch_op.drop_column('name555')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name555', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_users_name555', ['name555'])
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
