"""add colomn name1 to table roles

Revision ID: e77f78bde529
Revises: bb9a3eb8a5fb
Create Date: 2018-08-14 12:57:27.178338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f78bde529'
down_revision = 'bb9a3eb8a5fb'
branch_labels = None
depends_on = None
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name1', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_roles_id', ['name1'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roles_id', type_='unique')
        batch_op.drop_column('name1')

    # ### end Alembic commands ###
